FROM rust:1 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo install --path .

FROM gcr.io/distroless/cc-debian12
ARG GO_API_KEY
ENV GO_API_KEY=$GO_API_KEY
COPY --from=builder /usr/local/cargo/bin/smartGO-api .
COPY --from=builder /usr/src/app/app.db .
EXPOSE 8080
CMD ["./smartGO-api"]